x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "3"
services:
  bitcoind:
    container_name: "bitcoind"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SIGNET_TYPE: ${SIGNET_TYPE:-signet}
    user: "1000:1000"
    logging: *default-logging
    restart: always
    stop_grace_period: 1m
    volumes:
      - ~/volumes/.bitcoin:/home/bitcoin/.bitcoin
    environment:
      RPCPASSWORD: bitcoin
      BITCOIN_DIR: /home/bitcoin/.bitcoin
      SIGNET_TYPE: ${SIGNET_TYPE:-signet}
    ports:
      - "28332:28332"
      - "28333:28333"
      - "28334:28334"
      - "38332:38332"
      - "38333:38333"
      - "38334:38334"

  lit-init:
    container_name: "lit-init"
    image: lightninglabs/lndinit:v0.1.23-beta-lnd-v0.18.5-beta
    user: "1000:1000"
    volumes:
      - ./lnd-init.sh:/usr/local/bin/lnd-init.sh:ro
      - ~/volumes/.lnd:/home/lnd/.lnd
    environment:
      WALLET_DIR: "/home/lnd/.lnd/data/chain/bitcoin/signet"
      HOME: /home/lnd
    entrypoint: ""
    command: ["/bin/bash", "/usr/local/bin/lnd-init.sh"]

  lit:
    container_name: "lit"
    image: lightninglabs/lightning-terminal:v0.14.1-alpha
    user: "1000:1000"
    depends_on:
      - bitcoind
      - lit-init
    volumes:
      - ~/volumes/.lit:/home/lnd/.lit
      - ~/volumes/.lnd:/home/lnd/.lnd
      - ~/volumes/.tapd:/home/lnd/.tapd
      - ~/volumes/.faraday:/home/lnd/.faraday
      - ~/volumes/.loop:/home/lnd/.loop
      - ~/volumes/.pool:/home/lnd/.pool
      - ./lit-entrypoint.sh:/lit-entrypoint.sh:ro
    environment:
      HOME: /home/lnd
      EXTERNAL_IP: ${EXTERNAL_IP}
      NETWORK: ${NETWORK:-signet}
    entrypoint: /lit-entrypoint.sh
    ports:
      - "8443:8443"
      - "10009:10009"
      - "9735:9735"
      - "8080:8080"
      - "10029:10029"  # tapd RPC port

  lnbits:
    container_name: "lnbits"
    image: lnbits-nonroot:v1.2.1
    user: "1000:1000"
    depends_on:
      - lit
    environment:
      LNBITS_BACKEND_WALLET_CLASS: LndRestWallet
      LND_REST_ENDPOINT: https://lit:8080
      LND_REST_CERT: /app/.lnd/tls.cert
      LND_REST_MACAROON: /app/.lnd/data/chain/bitcoin/signet/admin.macaroon
      LNBITS_SITE_TITLE: "Mutinynet LNbits"
      LNBITS_SITE_TAGLINE: "Lightning on Mutinynet Signet"
      LNBITS_DATA_FOLDER: /app/data
      LNBITS_NETWORK: signet
      LNBITS_BASEURL: http://127.0.0.1:5000
      # Taproot Assets configuration
      TAPD_HOST: lit
      TAPD_PORT: 10009
      TAPD_NETWORK: signet
      TAPD_TLS_CERT_PATH: /app/.lnd/tls.cert
      TAPD_MACAROON_PATH: /app/.tapd/data/signet/admin.macaroon
    volumes:
      - ~/volumes/.lnbits:/app/data
      - ~/volumes/.lnd:/app/.lnd:ro
      - ~/volumes/.tapd:/app/.tapd:ro
    ports:
      - "5000:5000"
