version: "3.7"
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "3"
services:
  bitcoind:
    container_name: "bitcoind"
    build: .
    user: "0:1000"
    logging: *default-logging
    restart: always
    stop_grace_period: 1m
    volumes:
      - ~/volumes/.bitcoin:/root/.bitcoin
    environment:
      RPCPASSWORD: $RPCPASSWORD
    ports:
      - "28332:28332"
      - "28333:28333"
      - "28334:28334"
      - "38332:38332"
      - "38333:38333"
      - "38334:38334"

  lit-init:
    container_name: "lit-init"
    image: lightninglabs/lndinit:v0.1.23-beta-lnd-v0.18.5-beta
    volumes:
      - ./lnd-init.sh:/usr/local/bin/lnd-init.sh:ro
      - ~/volumes/.lnd:/root/.lnd
    environment:
      WALLET_DIR: "/root/.lnd/data/chain/bitcoin/signet"
    entrypoint: ""
    command: ["/bin/bash", "/usr/local/bin/lnd-init.sh"]

  lit:
    container_name: "lit"
    image: lightning-terminal:latest
    depends_on:
      - bitcoind
      - lit-init
    volumes:
      - ~/volumes/.lit:/root/.lit
      - ~/volumes/.lnd:/root/.lnd
    environment:
      LIT_CONFIG: |
        network=signet
        lnd-mode=integrated
        uipassword=your_secure_password
        httpslisten=0.0.0.0:8443
        lnd.rpclisten=0.0.0.0:10009
        lnd.restlisten=0.0.0.0:8080
        lnd.tlsextradomain=lit
        lnd.bitcoin.active=1
        lnd.bitcoin.node=bitcoind
        lnd.bitcoin.signet=1
        lnd.bitcoind.rpchost=bitcoind:38332
        lnd.bitcoind.rpcuser=bitcoin
        lnd.bitcoind.rpcpass=bitcoin
        lnd.bitcoind.zmqpubrawblock=tcp://bitcoind:28332
        lnd.bitcoind.zmqpubrawtx=tcp://bitcoind:28333
        lnd.rpcmiddleware.enable=true
        autopilot.disable=true
        taproot-assets-mode=integrated
        lnd.wallet-unlock-password-file=/root/.lnd/password.txt
    entrypoint: >
      sh -c "echo \"$$LIT_CONFIG\" > /root/.lit/lit.conf && litd"
    ports:
      - "8443:8443"
      - "10009:10009"
      - "9735:9735"
      - "8080:8080"

  lnbits:
    container_name: "lnbits"
    image: lnbitsdocker/lnbits-legend:latest
    volumes:
      - ~/volumes/.lnd:/root/.lnd:ro
    entrypoint: >
      sh -c "poetry run lnbits --port 5000 --host 0.0.0.0"
    environment:
      - LNBITS_BACKEND_WALLET_CLASS=LndRestWallet
      - LND_REST_ENDPOINT=https://lit:8080
      - LND_REST_CERT=/root/.lnd/tls.cert
      - LND_REST_MACAROON=/root/.lnd/data/chain/bitcoin/signet/admin.macaroon
      - LNBITS_NETWORK=signet
      - LNBITS_SITE_TITLE=MutinyNet LNBits
      - LNBITS_RESERVE_FEE_MIN=100
      - LNBITS_RESERVE_FEE_PERCENT=1.0
      - LNBITS_BASEURL=http://127.0.0.1:5000
        #- LNBITS_HOST=0.0.0.0
    ports:
      - "5000:5000"
    depends_on:
      - lit
