name: Simple Bitcoin Test

on:
  workflow_dispatch: # Manual trigger only

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test Bitcoin RPC
      run: |
        # Test connecting to existing Bitcoin node
        BITCOIN_HOST=104.248.7.46
        BITCOIN_USER=bitcoin
        BITCOIN_PASS=bitcoin
        
        echo "Testing Bitcoin RPC at $BITCOIN_HOST..."
        
        # Simple curl test
        curl -v -u $BITCOIN_USER:$BITCOIN_PASS \
          http://$BITCOIN_HOST:38332 \
          -d '{"method":"getblockcount","params":[],"id":1}' \
          -H 'Content-Type: application/json'