name: Test SSH Control

on:
  workflow_dispatch: # Manual trigger only

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup SSH
      run: |
        # Create SSH directory
        mkdir -p ~/.ssh
        
        # Add the private key from secrets
        echo "${{ secrets.DO_SSH_KEY }}" > ~/.ssh/mutinynet-ci
        chmod 600 ~/.ssh/mutinynet-ci
        
        # Add droplet to known hosts to avoid prompt
        ssh-keyscan -H 104.248.7.46 >> ~/.ssh/known_hosts 2>/dev/null
    
    - name: Test SSH connection
      run: |
        ssh -i ~/.ssh/mutinynet-ci root@104.248.7.46 "echo 'SSH from GitHub Actions works!'"
    
    - name: Check Bitcoin status
      run: |
        ssh -i ~/.ssh/mutinynet-ci root@104.248.7.46 "docker ps | grep bitcoin || echo 'Bitcoin not running'"
    
    - name: Stop Bitcoin gracefully
      run: |
        echo "Stopping Bitcoin..."
        ssh -i ~/.ssh/mutinynet-ci root@104.248.7.46 "cd /opt/mutinynet-litd-lnbits && docker-compose down || echo 'Docker-compose not found, trying docker stop'"
        ssh -i ~/.ssh/mutinynet-ci root@104.248.7.46 "docker stop bitcoind || echo 'Bitcoin already stopped'"
    
    - name: Verify stopped
      run: |
        ssh -i ~/.ssh/mutinynet-ci root@104.248.7.46 "docker ps | grep bitcoin && echo 'ERROR: Bitcoin still running!' || echo 'Bitcoin successfully stopped'"